# Generated by Django 5.2.4 on 2026-02-11 13:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('student_status', models.CharField(choices=[('NEW', 'New Student'), ('RETURNING', 'Returning (Old) Student')], default='NEW', max_length=20)),
                ('student_type', models.CharField(choices=[('DAY', 'Day Student'), ('BOARDING', 'Boarding Student')], default='DAY', max_length=20)),
                ('current_term', models.CharField(default='1st Term', max_length=20)),
                ('current_session', models.CharField(default='2025/2026', max_length=20)),
                ('parent_name', models.CharField(blank=True, default='', max_length=100)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_boarding', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_grade', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('student_status', models.CharField(choices=[('NEW', 'New Student'), ('RETURNING', 'Returning (Old) Student')], default='NEW', max_length=20)),
                ('student_type', models.CharField(choices=[('DAY', 'Day Student'), ('BOARDING', 'Boarding Student')], default='DAY', max_length=20)),
                ('current_term', models.CharField(default='1st Term', max_length=20)),
                ('current_session', models.CharField(default='2025/2026', max_length=20)),
                ('parent_name', models.CharField(blank=True, default='', max_length=100)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_boarding', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student',
                'verbose_name_plural': 'historical students',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
