# Generated by Django 5.2.4 on 2026-02-12 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_historicalstudent_id_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='date_of_admission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='lga',
            field=models.CharField(blank=True, max_length=50, verbose_name='LGA'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Allergies, etc.'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='nationality',
            field=models.CharField(default='Nigerian', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='parent_address',
            field=models.TextField(blank=True, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='passport_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='relationship_to_student',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='lga',
            field=models.CharField(blank=True, max_length=50, verbose_name='LGA'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Allergies, etc.'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Nigerian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_address',
            field=models.TextField(blank=True, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_passports/'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='relationship_to_student',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Guardian Name'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='student_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('NEW', 'New Admission'), ('RETURNING', 'Returning')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Guardian Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('NEW', 'New Admission'), ('RETURNING', 'Returning')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20)),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('student_status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('NEW', 'New Admission'), ('RETURNING', 'Returning')], max_length=20)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Academic History',
                'ordering': ['-academic_session'],
            },
        ),
    ]
