# Generated by Django 6.0.2 on 2026-03-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_historicalstudent_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='is_boarding',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_boarding',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
    ]
