[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd .."

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi --log-file -"
healthcheckPath = "/api/login/"
