# Generated by Django 5.2.4 on 2026-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('PRINCIPAL', 'Principal'), ('ACCOUNT_OFFICER', 'Account Officer'), ('CASHIER', 'Cashier'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin')], default='TEACHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('PRINCIPAL', 'Principal'), ('ACCOUNT_OFFICER', 'Account Officer'), ('CASHIER', 'Cashier'), ('TEACHER', 'Teacher'), ('SUPER_ADMIN', 'Super Admin')], default='TEACHER', max_length=20),
        ),
    ]
