# Generated by Django 5.2.4 on 2026-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_extracurricularactivity_alter_announcement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('ARTS', 'Arts & Culture'), ('ACADEMIC', 'Academic Club'), ('COMMUNITY', 'Community Service'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
