# Generated by Django 5.2.4 on 2026-02-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_historicaltransaction_payment_method_and_more'),
        ('inventory', '0001_initial'),
        ('students', '0003_historicalstudent_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalsupply',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase Price', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this'),
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='release_type',
            field=models.CharField(choices=[('SOLD', 'Sold to Student'), ('ISSUED', 'Issued to Staff/Dept'), ('DAMAGED', 'Damaged/Expired')], default='SOLD', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.student'),
        ),
        migrations.AddField(
            model_name='historicalrelease',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Auto-generated income record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='historicalsupply',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Auto-generated expense record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.expense'),
        ),
        migrations.AddField(
            model_name='historicalsupply',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit at purchase', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase Price', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this'),
        ),
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('SOLD', 'Sold to Student'), ('ISSUED', 'Issued to Staff/Dept'), ('DAMAGED', 'Damaged/Expired')], default='SOLD', max_length=20),
        ),
        migrations.AddField(
            model_name='release',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='release',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Auto-generated income record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='supply',
            name='expense',
            field=models.ForeignKey(blank=True, help_text='Auto-generated expense record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.expense'),
        ),
        migrations.AddField(
            model_name='supply',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit at purchase', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalrelease',
            name='recipient_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='recipient_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='historicalsupply',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
