# Generated by Django 5.2.4 on 2026-02-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_remove_historicalsupply_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='historicalsupply',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='unit_cost',
        ),
    ]
