# Generated by Django 5.2.4 on 2026-03-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrelease',
            name='release_type',
            field=models.CharField(choices=[('SOLD', 'Sold to Student'), ('ISSUED', 'Issued to Staff/Dept'), ('DAMAGED', 'Damaged/Expired'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='SOLD', max_length=20),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('SOLD', 'Sold to Student'), ('ISSUED', 'Issued to Staff/Dept'), ('DAMAGED', 'Damaged/Expired'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='SOLD', max_length=20),
        ),
    ]
