# Generated by Django 5.2.4 on 2026-02-13 12:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_historicalstudent_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGradeRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('test_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Test (20)')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Assign (10)')),
                ('midterm_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Mid-Term (20)')),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Exam (50)')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('grade', models.CharField(blank=True, editable=False, max_length=2)),
                ('remark', models.CharField(blank=True, editable=False, max_length=20)),
                ('term', models.CharField(default='1st Term', max_length=20)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.student')),
                ('allocation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.subjectallocation')),
            ],
            options={
                'verbose_name': 'historical grade record',
                'verbose_name_plural': 'historical grade records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Test (20)')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Assign (10)')),
                ('midterm_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Mid-Term (20)')),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Exam (50)')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('grade', models.CharField(blank=True, editable=False, max_length=2)),
                ('remark', models.CharField(blank=True, editable=False, max_length=20)),
                ('term', models.CharField(default='1st Term', max_length=20)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjectallocation')),
            ],
            options={
                'unique_together': {('student', 'allocation', 'term', 'session')},
            },
        ),
    ]
