# Generated by Django 5.2.4 on 2026-02-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0003_historicalstudent_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalgraderecord',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('term', models.CharField(default='1st Term', max_length=20)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('principal_comment', models.TextField(blank=True)),
                ('affective_domain', models.JSONField(blank=True, default=dict)),
                ('psychomotor_domain', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'session', 'term')},
            },
        ),
    ]
