# Generated by Django 6.0.2 on 2026-03-26 11:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalgraderecord',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='HistoricalLessonPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('materials', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('assessment_methods', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('support_file', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lesson plan',
                'verbose_name_plural': 'historical lesson plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('materials', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('assessment_methods', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('support_file', models.FileField(blank=True, null=True, upload_to='lesson_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.CharField(choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], max_length=20)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('term', models.CharField(default='1st Term', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
