# Generated by Django 5.2.4 on 2026-02-11 13:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. School Fees, Uniform, Books', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('class_grade', models.CharField(blank=True, choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], help_text='Leave blank if applies to all classes', max_length=20, null=True)),
                ('student_status', models.CharField(blank=True, choices=[('NEW', 'New Student'), ('RETURNING', 'Returning (Old) Student')], help_text='New vs Returning', max_length=20, null=True)),
                ('student_type', models.CharField(blank=True, choices=[('DAY', 'Day Student'), ('BOARDING', 'Boarding Student')], help_text='Day vs Boarding', max_length=20, null=True)),
                ('term', models.CharField(default='1st Term', max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFeeStructure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. School Fees, Uniform, Books', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('class_grade', models.CharField(blank=True, choices=[('DAY_CARE', 'Day Care'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('NURSERY_3', 'Nursery 3'), ('PRIMARY_1', 'Primary 1'), ('PRIMARY_2', 'Primary 2'), ('PRIMARY_3', 'Primary 3'), ('PRIMARY_4', 'Primary 4'), ('PRIMARY_5', 'Primary 5'), ('PRIMARY_6', 'Primary 6'), ('JSS_1', 'JSS 1'), ('JSS_2', 'JSS 2'), ('JSS_3', 'JSS 3'), ('SS_1', 'SS 1'), ('SS_2', 'SS 2'), ('SS_3', 'SS 3'), ('SIXTH_FORM', 'Sixth Form')], help_text='Leave blank if applies to all classes', max_length=20, null=True)),
                ('student_status', models.CharField(blank=True, choices=[('NEW', 'New Student'), ('RETURNING', 'Returning (Old) Student')], help_text='New vs Returning', max_length=20, null=True)),
                ('student_type', models.CharField(blank=True, choices=[('DAY', 'Day Student'), ('BOARDING', 'Boarding Student')], help_text='Day vs Boarding', max_length=20, null=True)),
                ('term', models.CharField(default='1st Term', max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fee structure',
                'verbose_name_plural': 'historical fee structures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudentFee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('total_amount_payable', models.DecimalField(decimal_places=2, default=0.0, help_text='Total bill for this term', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.student')),
            ],
            options={
                'verbose_name': 'historical student fee',
                'verbose_name_plural': 'historical student fees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(db_index=True, max_length=50)),
                ('date_paid', models.DateTimeField(blank=True, editable=False)),
                ('description', models.TextField(blank=True, help_text='Notes about the payment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.student')),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('total_amount_payable', models.DecimalField(decimal_places=2, default=0.0, help_text='Total bill for this term', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Notes about the payment')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='students.student')),
            ],
        ),
    ]
