# Generated by Django 5.2.4 on 2026-02-12 09:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='student_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('NEW', 'New Admission'), ('RETURNING', 'Returning')], help_text='New vs Returning', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeestructure',
            name='student_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('NEW', 'New Admission'), ('RETURNING', 'Returning')], help_text='New vs Returning', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('date_incurred', models.DateField()),
                ('receipt_doc', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('term', models.CharField(default='1st Term', max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('date_incurred', models.DateField()),
                ('receipt_doc', models.TextField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(default='1st Term', max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.expensecategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expense',
                'verbose_name_plural': 'historical expenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=100)),
                ('term', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='accounting.expense')),
                ('student_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='accounting.transaction')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
