# Generated by Django 5.2.4 on 2026-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_expensecategory_alter_feestructure_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='payment_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('BOARDING', 'Boarding Fees'), ('ADMISSION', 'Admission Fees'), ('PTA', 'PTA Levey'), ('EXAM', 'Exam Fees'), ('DEVELOPMENT', 'Development Levy'), ('UNIFORM', 'Uniforms'), ('BOOKS', 'Books'), ('OTHERS', 'Other Levies')], default='TUITION', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='session',
            field=models.CharField(default='2025/2026', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='term',
            field=models.CharField(default='1st Term', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('BOARDING', 'Boarding Fees'), ('ADMISSION', 'Admission Fees'), ('PTA', 'PTA Levey'), ('EXAM', 'Exam Fees'), ('DEVELOPMENT', 'Development Levy'), ('UNIFORM', 'Uniforms'), ('BOOKS', 'Books'), ('OTHERS', 'Other Levies')], default='TUITION', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.CharField(default='2025/2026', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='term',
            field=models.CharField(default='1st Term', max_length=50),
        ),
    ]
