# Generated by Django 5.2.4 on 2026-03-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_historicaltransaction_payment_method_and_more'),
        ('inventory', '0004_historicalitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_purchases', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='expense',
            name='inventory_item_name',
            field=models.CharField(blank=True, help_text='Name of the inventory item purchased', max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='inventory_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity of items purchased', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='inventory_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_inventory_purchase',
            field=models.BooleanField(default=False, help_text='If True, this expense will auto-increase inventory stock'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='inventory_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='inventory_item_name',
            field=models.CharField(blank=True, help_text='Name of the inventory item purchased', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='inventory_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity of items purchased', null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='inventory_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='is_inventory_purchase',
            field=models.BooleanField(default=False, help_text='If True, this expense will auto-increase inventory stock'),
        ),
    ]
