# Generated by Django 6.0.2 on 2026-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expense_inventory_item_expense_inventory_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='historicalfeestructure',
            name='student_type',
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='payment_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('ADMISSION', 'Admission Fees'), ('PTA', 'PTA Levey'), ('EXAM', 'Exam Fees'), ('DEVELOPMENT', 'Development Levy'), ('UNIFORM', 'Uniforms'), ('BOOKS', 'Books'), ('OTHERS', 'Other Levies')], default='TUITION', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('ADMISSION', 'Admission Fees'), ('PTA', 'PTA Levey'), ('EXAM', 'Exam Fees'), ('DEVELOPMENT', 'Development Levy'), ('UNIFORM', 'Uniforms'), ('BOOKS', 'Books'), ('OTHERS', 'Other Levies')], default='TUITION', max_length=20),
        ),
    ]
